[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Inclusão das bibliotecas irmãs e de terceiros
lib_extra_dirs = 
    ../adcs
    ../eps-tc
    ../tt-c
    ../common

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit INA219 @ ^1.2.1
    askuric/Simple FOC @ ^2.3.0