[env:esp32dev]
platform = espressif32 @ 6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_extra_dirs = 
    ../adcs
    ../eps-tc
    ../tt-c
    ../common

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit INA219 @ ^1.2.1
    askuric/Simple FOC @ 2.2.3
    adafruit/RTClib @ ^2.1.3