; Estacao Terrena improvisada FCP-01 (2o ESP32 + SX1276)
; Uso: pio run -t upload --upload-port /dev/ttyUSBx

[env:esp32dev]
platform = espressif32 @ 6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
	sandeepmistry/LoRa @ ^0.8.0
